### ISSUE TITLE
Train.py Error:  Dimensions must be equal,

### ISSUE THREAD

**Issue by rubby33** [hit-computer/MTA-LSTM#3]
Hello:

I  use python 2.7 and tensor flow 1.4,  when I run python Train.py, the following error occurs.

Could you please help me ? Thanks @hit-computer 

#  The Error msg:
```
  Traceback (most recent call last):
  File "/Users/jiangwei/git/topic_essay/Train.py", line 260, in <module>
    tf.app.run()
  File "/Users/jiangwei/anaconda/envs/tensorflow-1.4-py2.7/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "/Users/jiangwei/git/topic_essay/Train.py", line 235, in main
    m = Model(is_training=True, config=config, filename='coverage_data')
  File "/Users/jiangwei/git/topic_essay/Train.py", line 122, in __init__
    (cell_output, state) = cell(tf.concat([inputs[:, time_step, :], mt], axis=1), state) 
  File "/Users/jiangwei/anaconda/envs/tensorflow-1.4-py2.7/lib/python2.7/site-packages/tensorflow/python/ops/rnn_cell_impl.py", line 183, in __call__
    return super(RNNCell, self).__call__(inputs, state)
  File "/Users/jiangwei/anaconda/envs/tensorflow-1.4-py2.7/lib/python2.7/site-packages/tensorflow/python/layers/base.py", line 575, in __call__
    outputs = self.call(inputs, *args, **kwargs)
  File "/Users/jiangwei/anaconda/envs/tensorflow-1.4-py2.7/lib/python2.7/site-packages/tensorflow/python/ops/rnn_cell_impl.py", line 1066, in call
    cur_inp, new_state = cell(cur_inp, cur_state)
  File "/Users/jiangwei/anaconda/envs/tensorflow-1.4-py2.7/lib/python2.7/site-packages/tensorflow/python/ops/rnn_cell_impl.py", line 891, in __call__
    output, new_state = self._cell(inputs, state, scope)
  File "/Users/jiangwei/anaconda/envs/tensorflow-1.4-py2.7/lib/python2.7/site-packages/tensorflow/python/ops/rnn_cell_impl.py", line 183, in __call__
    return super(RNNCell, self).__call__(inputs, state)
  File "/Users/jiangwei/anaconda/envs/tensorflow-1.4-py2.7/lib/python2.7/site-packages/tensorflow/python/layers/base.py", line 575, in __call__
    outputs = self.call(inputs, *args, **kwargs)
  File "/Users/jiangwei/anaconda/envs/tensorflow-1.4-py2.7/lib/python2.7/site-packages/tensorflow/python/ops/rnn_cell_impl.py", line 611, in call
    lstm_matrix = self._linear1([inputs, m_prev])
  File "/Users/jiangwei/anaconda/envs/tensorflow-1.4-py2.7/lib/python2.7/site-packages/tensorflow/python/ops/rnn_cell_impl.py", line 1189, in __call__
    res = math_ops.matmul(array_ops.concat(args, 1), self._weights)
  File "/Users/jiangwei/anaconda/envs/tensorflow-1.4-py2.7/lib/python2.7/site-packages/tensorflow/python/ops/math_ops.py", line 1891, in matmul
    a, b, transpose_a=transpose_a, transpose_b=transpose_b, name=name)
  File "/Users/jiangwei/anaconda/envs/tensorflow-1.4-py2.7/lib/python2.7/site-packages/tensorflow/python/ops/gen_math_ops.py", line 2437, in _mat_mul
    name=name)
  File "/Users/jiangwei/anaconda/envs/tensorflow-1.4-py2.7/lib/python2.7/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/Users/jiangwei/anaconda/envs/tensorflow-1.4-py2.7/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 2958, in create_op
    set_shapes_for_outputs(ret)
  File "/Users/jiangwei/anaconda/envs/tensorflow-1.4-py2.7/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 2209, in set_shapes_for_outputs
    shapes = shape_func(op)
  File "/Users/jiangwei/anaconda/envs/tensorflow-1.4-py2.7/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 2159, in call_with_requiring
    return call_cpp_shape_fn(op, require_shape_fn=True)
  File "/Users/jiangwei/anaconda/envs/tensorflow-1.4-py2.7/lib/python2.7/site-packages/tensorflow/python/framework/common_shapes.py", line 627, in call_cpp_shape_fn
    require_shape_fn)
  File "/Users/jiangwei/anaconda/envs/tensorflow-1.4-py2.7/lib/python2.7/site-packages/tensorflow/python/framework/common_shapes.py", line 691, in _call_cpp_shape_fn_impl
    raise ValueError(err.message)
ValueError: Dimensions must be equal, but are 40 and 220 for 'model/RNN/RNN_sentence/RNN_sentence/multi_rnn_cell/cell_0/cell_0/lstm_cell/MatMul_1' (op: 'MatMul') with input shapes: [16,40], [220,80].

Process finished with exit code 1
```

#  The config file is
 
```
    class Config(object):
    data_dir = 'Data/'
    #vec_file = 'Data/wiki-zh.word2vec.txt'
    vec_file = 'Data/TrainingData.word2vec.txt'
    init_scale = 0.04
    learning_rate = 0.001
    max_grad_norm = 10 #gradient clipping
    num_layers = 2
    num_steps = 151 
    hidden_size = 20
    #word_embedding_size = 10
    word_embedding_size = 100
    max_epoch = 30
    max_max_epoch = 80
    keep_prob = 0.5 #The probability that each element is kept through dropout layer
    lr_decay = 1.0
    batch_size = 16 
    vocab_size = 92161 
    num_keywords = 5
    save_freq = 10 #The step (counted by the number of iterations) at which the model is saved to hard disk.
    model_path = './Model_News' #the path of model that need to save or load
    
    # parameter for generation
    len_of_generation = 16 #The number of characters by generated
    save_time = 20 #load save_time saved models
    is_sample = True #true means using sample, if not using argmax
    BeamSize = 2
```

**Comment by babyhuzi111** [comment]
same question~

**Comment by AIwem** [comment]
hidden_size = 600   # 是emb的两倍
 word_embedding_size = 300   # 词向量的维度

**Comment by syw1996** [comment]
这可能是0.12迁移1.4.0版本的问题

**Comment by syw1996** [comment]
def create_LSTM_cell():
            LSTM_cell = tf.nn.rnn_cell.LSTMCell(size, forget_bias=0.0, state_is_tuple=False)
            if is_training and config.keep_prob < 1:
                LSTM_cell = tf.nn.rnn_cell.DropoutWrapper(
                    LSTM_cell, output_keep_prob=config.keep_prob)
            return LSTM_cell
        # tensorflow 1.4.0需要修改 ！！！
        layers = [create_LSTM_cell() for _ in range(config.num_layers)]
        cell = tf.nn.rnn_cell.MultiRNNCell(layers, state_is_tuple=False)

**Comment by syw1996** [comment]
将Train.py和Generation.py创建cell部分均修改成这样即可

**Comment by syw1996** [comment]
I have reported this Bug to my teacher xcFeng, hope to update the codes as soon as possible.

**Comment by hit-computer** [comment]
@syw1996  Thank you very much!

**Comment by TobiasLee** [comment]
@syw1996 Thanks for the solution, you may make a PR to fix this?

**Comment by lxy444** [comment]
> hidden_size = 600 # 是emb的两倍
> word_embedding_size = 300 # 词向量的维度

请问是必须保持`hidden_size`是`word_embedding_size`的两倍吗

**Comment by lxy444** [comment]
@hit-computer

**Comment by hit-computer** [comment]
@lxy444 这个只是建议参数，不是必须的
